AVX-18292: Retry initial setup if status is 'not run'
AviatrixSystems/Controller-HA-for-AWS pull request #73
Opened 2022-01-12 18:23 UTC by kzhangavtx

2022-01-12 18:27 UTC, arvindsree requested changes
Initial_setup should only be run once

2022-01-14 00:49 UTC, arvindsree approved these changes

2022-01-14 00:49 UTC, arvindsree commented
Could you update description as well to summarize the changes

2022-01-14 23:51 UTC, kzhangavtx commented
> Could you update description as well to summarize the changes

Sure, added description.

2022-01-14 23:51 UTC, merged